global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'producto-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8090']
        labels:
          application: 'Producto Service Application'
  - job_name: 'inventario-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8092' ]
        labels:
          application: 'Inventario Service Application'
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8086' ]
        labels:
          application: 'Notification Service Application'


